[package]
name = "cellar-api"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
base64 = "=0.22.1"
cellar-auth = { path = "../cellar-auth" }
cellar-core = { path = "../cellar-core" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
async-trait.workspace = true
cellar-config = { path = "../cellar-config" }
cellar-db = { path = "../cellar-db" }
futures-util = "0.3.33"
http-body-util = "=0.1.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tempfile = "=3.27.0"
tokio.workspace = true
tower = { version = "=0.5.3", features = ["util"] }
